export const itemsData = [
    {
      items_id:1,
      items_name: 'airpod',
      items_description:'Apple Airpods',
      items_price:'1500 coins',
      items_qty:'2',
      items_category:'tech',
      items_purchasetype:'cod',
    },
    {
      items_id:2,
      items_name: 'iphone 14',
      items_description:'Apple Mobiles',
      items_price:'30000 coins',
      items_qty:'1',
      items_category:'tech',
      items_purchasetype:'online payment',
    },
    {
      items_id:3,
      items_name: 'earbuds',
      items_description:'Apple earbuds',
      items_price:'4500 coins',
      items_qty:'6',
      items_category:'tech',
      items_purchasetype:'cod',
    },
    {
      items_id:4,
      items_name: 'tab',
      items_description:'Apple mini tab',
      items_price:'55000 coins',
      items_qty:'3',
      items_category:'tech',
      items_purchasetype:'online payment',
    },
    {
      items_id:5,
      items_name: 'apple charger',
      items_description:'20w Apple charger',
      items_price:'7500 coins',
      items_qty:'2',
      items_category:'tech',
      items_purchasetype:'cod',
    }, 
]